---
title: "Data Products Week 3 Assignment"
author: "Henry CY Wong"
date: "2021-04-25"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Introduction

The objective of this assignment is to create an interactive chart with using **Plotly** in R Markdown. The dataset **mtcars** will be used for corresponding demonstration.

## Build Chart with Plotly

- Load **Plotly** Library:

```{r load_lib, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}
library(plotly)
```

- Load **mtcars** Dataset:

```{r load_data, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}
data("mtcars")
```

## Build Chart with Plotly, Continued

- Build the Chart with **Plotly** as shown below:

```{r show_command, eval=FALSE, echo=TRUE}
xlab <- list(title = "Horse Power")
ylab <- list(title = "Miles per Gallon")
fig <-plot_ly(mtcars, 
              x = mtcars$mpg, 
              y = mtcars$hp, 
              color = factor(mtcars$cyl), 
              size = mtcars$wt, 
              mode = "markers", 
              type = "scatter")
fig <- fig %>% layout(xaxis = xlab, yaxis = ylab)
fig
```

## Build Chart with Plotly, Continued

```{r build_chart, echo=FALSE, warning=FALSE, error=FALSE}
xlab <- list(title = "Horse Power")
ylab <- list(title = "Miles per Gallon")
fig <- plot_ly(mtcars, x = mtcars$mpg, y = mtcars$hp, color = factor(mtcars$cyl), size = mtcars$wt, mode = "markers", type = "scatter")
fig <- fig %>% layout(xaxis = xlab, yaxis = ylab)
fig
```